apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-cons-backend-deploy
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: denimallel/prod-cons-api:{{version}}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8091
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 8090
